### ISSUE TITLE
Doesn't work on 1.20.4

### ISSUE THREAD

**Issue by FaultyFunctions** [PhoenixOrigin/PlayerHider#1]
Hello! I tried running your mod on 1.20.4 and got this error:
![image](https://github.com/PhoenixOrigin/PlayerHider/assets/6508045/cd80d465-11ac-4e1e-9c03-43ce6b09e5de)

I am using the version published April 9th, 2024. Since they both say version 1.0 on Modrinth.

**Comment by PhoenixOrigin** [comment]
> Hello! I tried running your mod on 1.20.4 and got this error:
> 
> ![image](https://github.com/PhoenixOrigin/PlayerHider/assets/6508045/cd80d465-11ac-4e1e-9c03-43ce6b09e5de)
> 
> 
> 
> I am using the version published April 9th, 2024. Since they both say version 1.0 on Modrinth.
> 
> 

i'll update it to 1.20.4 later today

**Comment by PhoenixOrigin** [comment]
Hi, sorry about the delay! I believe 1.20.4 should work with V1.0.1 now.
